book_summary_site/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

book_summary_site/book_summary/urls.py
from django.urls import path
from . import views


app_name = 'book_summary'

urlpatterns = [
    path('',views.BookListView.as_view(),name='book_list'),
    path('book/add/',views.BookAddView.as_view(),name='book_add'),
    path('book/<int:pk>/update/',views.BookUpdateView.as_view(),name='book_update'),
    path('book/<int:pk>/',views.BookDetailView.as_view(),name='book_detail'),
    path('book/<int:pk>/delete/',views.BookDeleteView.as_view(),name='book_delete'),
    path('book/<int:book_pk>/comment/',views.CommentView.as_view(),name='comment'),
    path('comment/<int:pk>/delete/',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('topcategory/<int:pk>/',views.TopCategoryView.as_view(),name='topcategory'),
    path('bigcategory/<int:pk>/',views.BigCategoryView.as_view(),name='bigcategory'),
    path('category/<int:pk>/',views.CategoryView.as_view(),name='category'),
    path('publisher/<int:pk>/',views.PublisherView.as_view(),name='publisher'),
    path('author/<int:pk>/',views.AuthorView.as_view(),name='author'),
    #path('good/book/<int:pk>/',views.GoodBookView.as_view(),name='good_book'),
    #path('good/user/<int:pk>/',views.GoodUserView.as_view(),name='good_user'),

]

book_summary_site/book_summary_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_summary.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

book_summary_site/book_summary/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone


def set_default_topcategory():
    topcategory,_ = TopCategory.objects.get_or_create(name='None')
    return topcategory.pk

def set_default_bigcategory():
    bigcategory, _ = BigCategory.objects.get_or_create(name='None')
    return bigcategory.pk

def set_default_category():
    category, _ = Category.objects.get_or_create(name='None')
    return category.pk

def set_default_author():
    author, _ = Author.objects.get_or_create(name='unknown')
    return author.pk

def set_default_publisher():
    publisher, _ = Publisher.objects.get_or_create(name='None')
    return publisher.pk

class TopCategory(models.Model):
    name = models.CharField('大カテゴリ名',max_length=100)

    def __str__(self):
        return self.name
class BigCategory(models.Model):
    name = models.CharField('中カテゴリ名',max_length=100)
    topcategory = models.ForeignKey(TopCategory,on_delete=models.SET_DEFAULT,default=set_default_topcategory,verbose_name='大カテゴリ')
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField('小カテゴリ名',max_length=100)
    bigcategory = models.ForeignKey(BigCategory,on_delete=models.SET_DEFAULT,default=set_default_bigcategory,verbose_name='中カテゴリ')

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField('著者名',max_length=50)

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField('出版社名',max_length=50)
    author = models.ForeignKey(Author,on_delete=models.SET_DEFAULT,default=set_default_author)


    def __str__(self):
        return self.name

class Book(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL,null=True)
    title = models.CharField('タイトル',max_length=100)
    summary = models.TextField('要約')
    img = models.URLField('画像url',blank=True)
    link = models.URLField('Amazonリンク',blank=True)
    published_date = models.DateTimeField('公開日',auto_now=True)
    category = models.ForeignKey(Category,on_delete=models.SET_DEFAULT,default=set_default_category,blank=True,null=True,verbose_name='小カテゴリ')
    publisher = models.ForeignKey(Publisher,on_delete=models.SET_DEFAULT,default=set_default_publisher,blank=True,verbose_name='出版社')
    author = models.ForeignKey(Author,on_delete=models.SET_DEFAULT,default=set_default_author,blank=True)
        
    def __str__(self):
        return self.title
    


class Comment(models.Model):
    author = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL,null=True)
    title = models.CharField(verbose_name='投稿者',max_length=200,blank=True,default='名無しさん')
    comment = models.TextField(verbose_name='コメント')
    published_date = models.DateTimeField(verbose_name='公開日',auto_now=True)
    book = models.ForeignKey(Book,on_delete=models.SET_NULL,null=True)
    
    def __str__(self):
        return self.title

class Good(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL,null=True)
    book = models.ForeignKey(Book,on_delete=models.CASCADE)

book_summary_site/book_summary/forms.py
from django import forms
from .models import Book,Comment,TopCategory,BigCategory,Category,Publisher,Author


app_name = 'book_summary'

class BookCreateForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title','summary','author','publisher','category','img','link','user')


class CommentCreateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('title','comment')

book_summary_site/book_summary/views.py
from django.shortcuts import get_object_or_404,redirect
from django.views import generic
from .forms import BookCreateForm,CommentCreateForm
from .models import TopCategory,BigCategory,Category,Author,Publisher,Comment,Book
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

app_name = 'book_summary'

'''get_context_dataメソッドはテンプレートへ渡す辞書を作成するメソッドで、
ほとんどのクラスベースビューがこのメソッドを持っています。
辞書をカスタマイズしたい場合、テンプレートに渡す変数を増やしたい場合に上書きすることがあります。'''
class BookListView(generic.ListView):
    model = Book
    template_name = 'book_summary/book_list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Book.objects.order_by('-published_date')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(summary__icontains=keyword)
                )
        return queryset
    

class BookAddView(LoginRequiredMixin,generic.CreateView):
    model = Book
    form_class = BookCreateForm
    success_url = reverse_lazy('book_summary:book_list')
    template_name = 'book_summary/book_form.html'

class BookUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Book
    form_class = BookCreateForm
    template_name = 'book_summary/book_form.html'

    def get_success_url(self):
        return redirect('book_summary:book_detail',kwargs={'pk':self.kwargs['pk']}) 
        #　pkを取得して元のdetailに遷移

class BookDetailView(LoginRequiredMixin,generic.DetailView):
    model = Book
    template_name = 'book_summary/book_detail.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentCreateForm
        return context

class BookDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Book
    template_name = 'book_summary/book_delete.html'
    success_url = reverse_lazy('book_summary:book_list')

class CommentView(LoginRequiredMixin,generic.CreateView):
    model = Comment
    form_class = CommentCreateForm
    template_name = 'book_summary/book_detail.html'

    def form_valid(self,form):
        book_pk = self.kwargs['book_pk']
        comment = form.save(commit=False)
        comment.book = get_object_or_404(Book,pk=book_pk)
        comment = form.save()
        return redirect('book_summary:book_detail',pk=book_pk)

class CommentDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Comment
    template_name = 'book_summary/comment_delete.html'

    def get_success_url(self):
        comment = get_object_or_404(Comment,pk=self.kwargs['pk'])
        return redirect('book_summary:book_detail',pk=comment.book.pk)

class TopCategoryView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        topcategory = get_object_or_404(TopCategory,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(category__bigcategory__topcategory=topcategory)
        return queryset
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        topcategory = get_object_or_404(TopCategory,pk=self.kwargs['pk'])
        context['bigcategory_list'] =  topcategory.bigcategory_set.all
        context['topcategory'] = topcategory
        return context


class BigCategoryView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        bigcategory = get_object_or_404(BigCategory,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(category__bigcategory=bigcategory)
        return queryset

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        bigcategory = get_object_or_404(BigCategory,pk=self.kwargs['pk'])
        context['category_list'] = bigcategory.category_set.all
        context['bigcategory'] = bigcategory
        return context

class CategoryView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        category = get_object_or_404(Category,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(category=category)
        return queryset


class PublisherView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        publisher = get_object_or_404(Publisher,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(publisher=publisher)
        return queryset


class AuthorView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        author = get_object_or_404(Author,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(author=author)
        return queryset

book_summary_site/book_summary/templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        .dropdown-submenu {
          position: relative;
        }
        
        .dropdown-submenu .dropdown-menu {
          top: 0;
          left: 100%;
          margin-top: -1px;
        }
        </style>
    <title>Book Summary Site</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'book_summary:book_list' %}">BookList</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'book_summary:book_add' %}">本の投稿フォーム</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:user_detail' user.pk %}">こんにちは！{{user.name}} さん　マイページはこちら</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:logout' %}">ログアウト</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                      こんにちは！　ゲストさん
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:user_create' %}">新規登録</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:login' %}">ログイン</a>
                    </li>
                    {% endif %}
                  </ul>
                  <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'book_summary:book_list' %}">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </div>
              </nav>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
              <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                    大カテゴリ
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    {% for topcategory in topcategory_list %}
                    <li class="dropdown-submenu">
                      <a class="test" tabindex="-1" href="{% url 'book_summary:topcategory' topcategory.pk %}">{{topcategory}} <span class="caret"></span></a>
                    </li>
                    {% endfor %}
                  </ul>
              </div>
              <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                    出版社
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    {% for publisher in publisher_list %}
                    <li class="dropdown-submenu">
                      <a class="test" tabindex="-1" href="{% url 'book_summary:publisher' publisher.pk %}">{{publisher}} <span class="caret"></span></a>
                    </li>
                    {% endfor %}
                  </ul>
              </div>
              <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                    著者
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    {% for author in author_list %}
                    <li class="dropdown-submenu">
                      <a class="test" tabindex="-1" href="{% url 'book_summary:author' author.pk %}">{{author}} <span class="caret"></span></a>
                    </li>
                    {% endfor %}
                  </ul>
              </div>
          </div>
          <div class="col-md-8">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
  
    
      <script>
          $(document).ready(function(){
            $('.dropdown-submenu a.test').on("click", function(e){
              $(this).next('ul').toggle();
              e.stopPropagation();
              e.preventDefault();
            });
          });
          </script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>