book_summary_site/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

book_summary_site/book_summary/urls.py
from django.urls import path
from . import views


app_name = 'book_summary'

urlpatterns = [
    path('',views.BookListView.as_view(),name='book_list'),
    path('book/add/',views.BookAddView.as_view(),name='book_add'),
    path('book/<int:pk>/update/',views.BookUpdateView.as_view(),name='book_update'),
    path('book/<int:pk>/',views.BookDetailView.as_view(),name='book_detail'),
    path('book/<int:pk>/delete/',views.BookDeleteView.as_view(),name='book_delete'),
    path('book/<int:book_pk>/comment/',views.CommentView.as_view(),name='comment'),
    path('comment/<int:pk>/delete/',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('topcategory/<int:pk>/',views.TopCategoryView.as_view(),name='topcategory'),
    path('bigcategory/<int:pk>/',views.BigCategoryView.as_view(),name='bigcategory'),
    path('category/<int:pk>/',views.CategoryView.as_view(),name='category'),
    path('publisher/<int:pk>/',views.PublisherView.as_view(),name='publisher'),
    path('author/<int:pk>/',views.AuthorView.as_view(),name='author'),
    #path('good/book/<int:pk>/',views.GoodBookView.as_view(),name='good_book'),
    #path('good/user/<int:pk>/',views.GoodUserView.as_view(),name='good_user'),

]

book_summary_site/book_summary_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_summary.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

book_summary_site/book_summary/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone


def set_default_topcategory():
    topcategory,_ = TopCategory.objects.get_or_create(name='None')
    return topcategory.pk

def set_default_bigcategory():
    bigcategory, _ = BigCategory.objects.get_or_create(name='None')
    return bigcategory.pk

def set_default_category():
    category, _ = Category.objects.get_or_create(name='None')
    return category.pk

def set_default_author():
    author, _ = Author.objects.get_or_create(name='unknown')
    return author.pk

def set_default_publisher():
    publisher, _ = Publisher.objects.get_or_create(name='None')
    return publisher.pk

class TopCategory(models.Model):
    name = models.CharField('大カテゴリ名',max_length=100)

    def __str__(self):
        return self.name
class BigCategory(models.Model):
    name = models.CharField('中カテゴリ名',max_length=100)
    topcategory = models.ForeignKey(TopCategory,on_delete=models.SET_DEFAULT,default=set_default_topcategory,verbose_name='大カテゴリ')
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField('小カテゴリ名',max_length=100)
    bigcategory = models.ForeignKey(BigCategory,on_delete=models.SET_DEFAULT,default=set_default_bigcategory,verbose_name='中カテゴリ')

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField('著者名',max_length=50)

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField('出版社名',max_length=50)
    author = models.ForeignKey(Author,on_delete=models.SET_DEFAULT,default=set_default_author)


    def __str__(self):
        return self.name

class Book(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL,null=True)
    title = models.CharField('タイトル',max_length=100)
    summary = models.TextField('要約')
    img = models.URLField('画像url',blank=True)
    link = models.URLField('Amazonリンク',blank=True)
    published_date = models.DateTimeField('公開日',auto_now=True)
    category = models.ForeignKey(Category,on_delete=models.SET_DEFAULT,default=set_default_category,blank=True,null=True,verbose_name='小カテゴリ')
    publisher = models.ForeignKey(Publisher,on_delete=models.SET_DEFAULT,default=set_default_publisher,blank=True,verbose_name='出版社')
    author = models.ForeignKey(Author,on_delete=models.SET_DEFAULT,default=set_default_author,blank=True)
        
    def __str__(self):
        return self.title
    


class Comment(models.Model):
    author = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL,null=True)
    title = models.CharField(verbose_name='投稿者',max_length=200,blank=True,default='名無しさん')
    comment = models.TextField(verbose_name='コメント')
    published_date = models.DateTimeField(verbose_name='公開日',auto_now=True)
    book = models.ForeignKey(Book,on_delete=models.SET_NULL,null=True)
    
    def __str__(self):
        return self.title

class Good(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL,null=True)
    book = models.ForeignKey(Book,on_delete=models.CASCADE)

book_summary_site/accounts/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm,UserCreationForm,PasswordChangeForm,
PasswordResetForm,SetPasswordForm)
from django.contrib.auth import get_user_model



User = get_user_model()

class LoginForm(AuthenticationForm):

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email','name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        fields = ('name','profile')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更時のフォーム"""
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordResetForm(PasswordResetForm):
    """パスワードを忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class EmailChangeForm(forms.ModelForm):
    """メールアドレス変更フォーム"""

    class Meta:
        model = User
        fields = ('email',)
    
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

book_summary_site/accounts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.signing import BadSignature,SignatureExpired,loads,dumps
from django.http import Http404,HttpResponseBadRequest
from django.shortcuts import redirect,resolve_url
from django.template.loader import get_template
from django.urls import reverse_lazy
from .forms import (UserCreateForm,LoginForm,UserUpdateForm,MyPasswordChangeForm,
MyPasswordResetForm,MySetPasswordForm,EmailChangeForm)
from django.contrib.auth.views import (LoginView,LogoutView,PasswordChangeView,
PasswordChangeDoneView,PasswordResetView,PasswordResetDoneView,PasswordResetConfirmView,
PasswordResetCompleteView)
from django.views import generic


User = get_user_model()
class Login(LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'

class Logout(LoginRequiredMixin,LogoutView):
    template_name = 'accounts/logout.html'

class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'accounts/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('accounts/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('accounts/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        return redirect('accounts:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'accounts/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'accounts/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'accounts/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/user_form.html'

    def get_success_url(self):
        return resolve_url('accounts:user_detail', pk=self.kwargs['pk'])


class PasswordChange(PasswordChangeView):
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'accounts/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'accounts/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワードリセット用URLの送付ページ"""
    subject_template_name = 'accounts/mail_template/password_reset/subject.txt'
    email_template_name = 'accounts/mail_template/password_reset/message.txt'
    template_name = 'accounts/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワードリセット用URL送付完了ページ"""
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定完了ページ"""
    template_name = 'accounts/password_reset_complete.html'


class EmailChange(LoginRequiredMixin, generic.FormView):
    """メールアドレスの変更"""
    template_name = 'accounts/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data['email']

        # URLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }

        subject_template = get_template('accounts/mail_template/email_change/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('accounts/mail_template/email_change/message.txt')
        message = message_template.render(context)
        send_mail(subject, message, None, [new_email])

        return redirect('accounts:email_change_done')


class EmailChangeDone(LoginRequiredMixin, generic.TemplateView):
    """メールアドレスの変更メールを送ったよ"""
    template_name = 'accounts/email_change_done.html'


class EmailChangeComplete(LoginRequiredMixin, generic.TemplateView):
    """リンクを踏んだ後に呼ばれるメアド変更ビュー"""
    template_name = 'accounts/email_change_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            User.objects.filter(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)

book_summary_site/accounts/templates/accounts/email_change_complete.html
{% extends "base.html" %}
{% block content %}
<p>
    メールアドレスを変更しました。<br>
</p>
{% endblock %}

book_summary_site/accounts/templates/accounts/email_change_done.html
{% extends "base.html" %}
{% block content %}
<p>
    確認メールに記載されているリンクをクリックすると、アドレスが変更されます。
</p>
{% endblock %}

book_summary_site/accounts/templates/accounts/email_change_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

book_summary_site/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
<p>ログアウトしました。</p>
{% endblock %}

book_summary_site/accounts/templates/accounts/password_change.html
{% extends 'base.html'%}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

book_summary_site/accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}
{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

book_summary_site/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
<p>
    パスワード再設定を完了しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

book_summary_site/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

book_summary_site/accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

book_summary_site/accounts/templates/accounts/user_create.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

book_summary_site/accounts/templates/accounts/user_create_complete.html
{% extends 'base.html' %}
{% block content %}
<p>
本登録が完了しました。<br>
 登録されたメールアドレスとパスワードでログインしてください。<br>
<a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

book_summary_site/accounts/templates/accounts/user_create_done.html
{% extends 'base.html' %}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
</p>
{% endblock %}

book_summary_site/accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}
{% block content %}

<table class="table">
    <tbody>
        <tr>
            <th>メールアドレス</th>
            <td>{{ user.email }}</td>
            <td><a href="{% url 'accounts:email_change' %}">変更</a></td>
        </tr>
        <tr>
            <th>ユーザーネーム</th>
            <td>{{ user.name }}</td>
            <td><a href="{% url 'accounts:user_update' user.pk %}">変更</a></td>
        </tr>
        <br>
        <br>
        <th>投稿した本</th>
        {% for book in user.book_set.all %}
        <tr><td><a href="{% url 'book_summary:book_detail' book.pk %}">{{book.title}}</a></td></tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

book_summary_site/accounts/templates/accounts/user_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
        {{ form.non_field_errors }}
        <table class="table">
            <tbody>
                {% for field in form %}
                    <tr>
                        <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                        <td>{{ field }} {{ field.errors }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-lg" >送信</button>
    </form>
{% endblock %}