book_summary_site/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',views.Login.as_view(),name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

book_summary_site/book_summary/urls.py
from django.urls import path
from . import views


app_name = 'book_summary'

urlpatterns = [
    path('',views.BookListView.as_view(),name='book_list'),
    path('book/add/',views.BookAddView.as_view(),name='book_add'),
    path('book/<int:pk>/update/',views.BookUpdateView.as_view(),name='book_update'),
    path('book/<int:pk>/',views.BookDetailView.as_view(),name='book_detail'),
    path('book/<int:pk>/delete/',views.BookDeleteView.as_view(),name='book_delete'),
    path('book/<int:book_pk>/comment/',views.CommentView.as_view(),name='comment'),
    path('comment/<int:pk>/delete/',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('topcategory/<int:pk>/',views.TopCategoryView.as_view(),name='topcategory'),
    path('bigcategory/<int:pk>/',views.BigCategoryView.as_view(),name='bigcategory'),
    path('category/<int:pk>/',views.CategoryView.as_view(),name='category'),
    path('publisher/<int:pk>/',views.PublisherView.as_view(),name='publisher'),
    path('author/<int:pk>/',views.AuthorView.as_view(),name='author'),
    #path('good/book/<int:pk>/',views.GoodBookView.as_view(),name='good_book'),
    #path('good/user/<int:pk>/',views.GoodUserView.as_view(),name='good_user'),

]

book_summary_site/book_summary_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_summary.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

book_summary_site/book_summary/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone


def set_default_topcategory():
    topcategory,_ = TopCategory.objects.get_or_create(name='None')
    return topcategory.pk

def set_default_bigcategory():
    bigcategory, _ = BigCategory.objects.get_or_create(name='None')
    return bigcategory.pk

def set_default_category():
    category, _ = Category.objects.get_or_create(name='None')
    return category.pk

def set_default_author():
    author, _ = Author.objects.get_or_create(name='unknown')
    return author.pk

def set_default_publisher():
    publisher, _ = Publisher.objects.get_or_create(name='None')
    return publisher.pk

class TopCategory(models.Model):
    name = models.CharField('大カテゴリ名',max_length=100)

    def __str__(self):
        return self.name
class BigCategory(models.Model):
    name = models.CharField('中カテゴリ名',max_length=100)
    topcategory = models.ForeignKey(TopCategory,on_delete=models.SET_DEFAULT,default=set_default_topcategory,verbose_name='大カテゴリ')
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField('小カテゴリ名',max_length=100)
    bigcategory = models.ForeignKey(BigCategory,on_delete=models.SET_DEFAULT,default=set_default_bigcategory,verbose_name='中カテゴリ')

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField('著者名',max_length=50)

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField('出版社名',max_length=50)
    author = models.ForeignKey(Author,on_delete=models.SET_DEFAULT,default=set_default_author)


    def __str__(self):
        return self.name

class Book(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL,null=True)
    title = models.CharField('タイトル',max_length=100)
    summary = models.TextField('要約')
    img = models.URLField('画像url',blank=True)
    link = models.URLField('Amazonリンク',blank=True)
    published_date = models.DateTimeField('公開日',auto_now=True)
    category = models.ForeignKey(Category,on_delete=models.SET_DEFAULT,default=set_default_category,blank=True,null=True,verbose_name='小カテゴリ')
    publisher = models.ForeignKey(Publisher,on_delete=models.SET_DEFAULT,default=set_default_publisher,blank=True,verbose_name='出版社')
    author = models.ForeignKey(Author,on_delete=models.SET_DEFAULT,default=set_default_author,blank=True)
        
    def __str__(self):
        return self.title
    


class Comment(models.Model):
    author = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL,null=True)
    title = models.CharField(verbose_name='投稿者',max_length=200,blank=True,default='名無しさん')
    comment = models.TextField(verbose_name='コメント')
    published_date = models.DateTimeField(verbose_name='公開日',auto_now=True)
    book = models.ForeignKey(Book,on_delete=models.SET_NULL,null=True)
    
    def __str__(self):
        return self.title

class Good(models.Model):
    user = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL,null=True)
    book = models.ForeignKey(Book,on_delete=models.CASCADE)

book_summary_site/book_summary/forms.py
from django import forms
from .models import Book,Comment,TopCategory,BigCategory,Category,Publisher,Author


app_name = 'book_summary'

class BookCreateForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title','summary','author','publisher','category','img','link','user')


class CommentCreateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('title','comment')

book_summary_site/book_summary/views.py
from django.shortcuts import get_object_or_404,redirect
from django.views import generic
from .forms import BookCreateForm,CommentCreateForm
from .models import TopCategory,BigCategory,Category,Author,Publisher,Comment,Book
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

app_name = 'book_summary'

'''get_context_dataメソッドはテンプレートへ渡す辞書を作成するメソッドで、
ほとんどのクラスベースビューがこのメソッドを持っています。
辞書をカスタマイズしたい場合、テンプレートに渡す変数を増やしたい場合に上書きすることがあります。'''
class BookListView(generic.ListView):
    model = Book
    template_name = 'book_summary/book_list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Book.objects.order_by('-published_date')
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(summary__icontains=keyword)
                )
        return queryset
    

class BookAddView(LoginRequiredMixin,generic.CreateView):
    model = Book
    form_class = BookCreateForm
    success_url = reverse_lazy('book_summary:book_list')
    template_name = 'book_summary/book_form.html'

class BookUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Book
    form_class = BookCreateForm
    template_name = 'book_summary/book_form.html'

    def get_success_url(self):
        return redirect('book_summary:book_detail',kwargs={'pk':self.kwargs['pk']}) 
        #　pkを取得して元のdetailに遷移

class BookDetailView(LoginRequiredMixin,generic.DetailView):
    model = Book
    template_name = 'book_summary/book_detail.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentCreateForm
        return context

class BookDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Book
    template_name = 'book_summary/book_delete.html'
    success_url = reverse_lazy('book_summary:book_list')

class CommentView(LoginRequiredMixin,generic.CreateView):
    model = Comment
    form_class = CommentCreateForm
    template_name = 'book_summary/book_detail.html'

    def form_valid(self,form):
        book_pk = self.kwargs['book_pk']
        comment = form.save(commit=False)
        comment.book = get_object_or_404(Book,pk=book_pk)
        comment = form.save()
        return redirect('book_summary:book_detail',pk=book_pk)

class CommentDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Comment
    template_name = 'book_summary/comment_delete.html'

    def get_success_url(self):
        comment = get_object_or_404(Comment,pk=self.kwargs['pk'])
        return redirect('book_summary:book_detail',pk=comment.book.pk)

class TopCategoryView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        topcategory = get_object_or_404(TopCategory,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(category__bigcategory__topcategory=topcategory)
        return queryset
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        topcategory = get_object_or_404(TopCategory,pk=self.kwargs['pk'])
        context['bigcategory_list'] =  topcategory.bigcategory_set.all
        context['topcategory'] = topcategory
        return context


class BigCategoryView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        bigcategory = get_object_or_404(BigCategory,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(category__bigcategory=bigcategory)
        return queryset

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        bigcategory = get_object_or_404(BigCategory,pk=self.kwargs['pk'])
        context['category_list'] = bigcategory.category_set.all
        context['bigcategory'] = bigcategory
        return context

class CategoryView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        category = get_object_or_404(Category,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(category=category)
        return queryset


class PublisherView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        publisher = get_object_or_404(Publisher,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(publisher=publisher)
        return queryset


class AuthorView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        author = get_object_or_404(Author,pk=self.kwargs['pk'])
        queryset = Book.objects.order_by('-published_date').filter(author=author)
        return queryset

book_summary_site/book_summary/templates/book_summary/book_delete.html
{% extends 'base.html' %}
{% block content %}
<p>{{book.title}}を削除しました。</p>
<a href="{% url 'book_summary:index' %}">Toppageへ戻る</a>
{% endblock %}

book_summary_site/book_summary/templates/book_summary/book_detail.html
{% extends 'base.html' %}
{% block content %}
<table>
        <tr><td><h1>{{book.title}}</h1></td>
            <td><td><a href="{% url 'book_summary:book_update' book.pk %}">編集</a></td></td>
            <td><td><a href="{% url 'book_summary:book_delete' book.pk %}">削除</a></td></td></tr>
        <tr><td>{{book.summary|linebreaksbr}}</td></tr>
        <tr><td>著者:{{book.author}}</td></tr>
        <tr><td>出版社:{{book.publisher}}</td></tr>
        <tr><td>大カテゴリ:<a href="{% url 'book_summary:topcategory' book.category.bigcategory.topcategory.pk %}">{{book.category.bigcategory.topcategory}}</a></td>
            <td>中カテゴリ:<a href="{% url 'book_summary:bigcategory' book.category.bigcategory.pk %}">{{book.category.bigcategory}}  </a></td>
            <td><td>小カテゴリ:<a href="{% url 'book_summary:category' book.category.pk %}">{{book.category}}</a></td></td></tr>
        {% if book.link %}
        <td>Amazonへのリンク:{{book.link}}</td>
        {% endif %}
        {% if book.img %}
        <img src="{{book.img}}">
        {% endif %}
        <td>{{book.published_date}}</td>
        
</table>
<form action="{% url 'book_summary:comment' book.pk %}" method="POST">
    {{form.non_field_errors}}
    {% for field in form %}
    <div class="form-group">
        <label for="{{field.id_for_label}}">{{field.label_tag}}</label>
        {{field}}
        {{field.errors}}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-dark">送信</button>
</form>
{% for comment in book.comment_set.all %}
<p>
    {{comment.title}}<br>
    {{comment.comment|linebreaksbr}}<br>

    {% if user.is_authenticated %}
    <form action="{% url 'book_summary:comment_delete' comment.pk %}" method="POST">
        <button type="submit">このコメントを削除</button>
        {% csrf_token %}
    </form>
    {% endif %}
</p>
{% endfor %}
{% include 'book_summary/page.html' %}
{% endblock %}

book_summary_site/book_summary/templates/book_summary/book_form.html
{% extends 'base.html' %}
{% block content %}
<h1>BookForm</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">投稿</button>
</form>
{% endblock %}

book_summary_site/book_summary/templates/book_summary/book_list.html
{% extends 'base.html' %}
{% block content %}
{% if bigcategory_list %}
<h1>{{topcategory}}</h1>
<table>
    <tr><td>中カテゴリ</td></tr>
    {% for bigcategory in bigcategory_list %}
    <tr><td><a href="{% url 'book_summary:bigcategory' bigcategory.pk %}">{{bigcategory}}</a></td></tr>
    {% endfor %}
</table>

{% elif category_list %}
<h1>{{bigcategory}}</h1>
<table>
    <tr><td>小カテゴリ</td></tr>
    {% for category in category_list %}
    <tr><td><a href="{% url 'book_summary:category' category.pk %}">{{category}}</a></td></tr>
    {% endfor %}
</table>
{% endif %}


<h1>BookList</h1>
{% for book in book_list %}
<table>
<tr><td><a href="{% url 'book_summary:book_detail' book.pk %}">{{book.title}}</a></td>
</tr>
</table>
{% endfor %}

{% include 'book_summary/page.html' %}
{% endblock %}

book_summary_site/book_summary/templates/book_summary/comment_delete.html
{% extends 'base.html' %}
{% block content %}
コメントを削除しました。
<a href="{% url 'book_summary:book_detail' book.pk %}">元のページへ戻る</a>
{% endblock %}

book_summary_site/book_summary/templates/book_summary/index.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}

book_summary_site/book_summary/templates/book_summary/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>